export default [
    {
        name: "Dashboard",
        path: "/",
        component: () => import("@/views/Dashboard"),
        meta: { layout: "default", requiresAuth: true },
    },
    {
        name: "Account",
        path: "/account",
        component: () => import("@/views/Account"),
        meta: { layout: "default", requiresAuth: true },
    },
    {
        name: "Referrals",
        path: "/referrals",
        component: () => import("@/views/Referrals"),
        meta: { layout: "default", requiresAuth: true },
    },
    {
        name: "Loan Request",
        path: "/loan-request",
        component: () => import("@/views/LoanRequest"),
        meta: { layout: "default", requiresAuth: true },
    },
    {
        name: "Transaction Page",
        path: "/transaction-page",
        component: () => import("@/views/TransactionPage"),
        meta: { layout: "default", requiresAuth: true },
    },
    { name: "Help", path: "/help", component: () => import("@/views/Help"), meta: { layout: "default" } },
    {
        name: "Repayment",
        path: "/repayment",
        component: () => import("@/views/Repayment"),
        meta: { layout: "default", requiresAuth: true },
    },
    {
        name: "Settings",
        path: "/settings",
        component: () => import("@/views/Settings"),
        meta: { layout: "default", requiresAuth: true },
    },
    { name: "Login", path: "/login", component: () => import("@/views/Login"), meta: { layout: "authentication" } },
    {
        name: "Register",
        path: "/register",
        component: () => import("@/views/Register"),
        meta: { layout: "authentication" },
    },
    {
        name: "Forgot Password",
        path: "/forgot-password",
        component: () => import("@/views/ForgotPassword"),
        meta: { layout: "authentication" },
    },
    {
        name: "Verify Email",
        path: "/verify-email",
        component: () => import("@/views/VerifyEmail"),
        meta: { layout: "authentication" },
    },
    {
        name: "Reset Password",
        path: "/reset-password",
        component: () => import("@/views/CreatePassword"),
        meta: { layout: "authentication" },
    },
];
